[project]
name = "terminusgps-notifier"
description = "Terminus GPS Notification Service"
readme = "README.md"
version = "1.2.0"
requires-python = ">=3.12"

authors = [
    { name = "Blake Nall", email = "blake@terminusgps.com" },
    { name = "Lili Noack", email = "lili@terminusgps.com" },
]
dependencies = [
    "aiohttp-retry==2.8.3",
    "aiohttp==3.10.11",
    "aiosignal==1.3.1",
    "annotated-types==0.7.0",
    "anyio==4.4.0",
    "attrs==23.2.0",
    "certifi==2024.07.04",
    "charset-normalizer==3.3.2",
    "click==8.1.7",
    "dnspython==2.6.1",
    "email-validator==2.1.1",
    "fastapi==0.115.8",
    "fastapi-cli==0.0.4",
    "frozenlist==1.4.1",
    "future==1.0.0",
    "h11==0.14.0",
    "httpcore==1.0.5",
    "httptools==0.6.4",
    "httpx==0.27.0",
    "idna==3.7",
    "jinja2==3.1.5",
    "jmespath==1.0.1",
    "markdown-it-py==3.0.0",
    "markupsafe==2.1.5",
    "mdurl==0.1.2",
    "multidict==6.0.5",
    "orjson==3.10.15",
    "phonenumbers==8.13.38",
    "pydantic==2.10.6",
    "pydantic-core==2.27.2",
    "pygments==2.18.0",
    "pyjwt==2.8.0",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.0.1",
    "python-multipart==0.0.18",
    "python-wialon==1.2.4",
    "pyyaml==6.0.1",
    "requests==2.32.3",
    "rich==13.7.1",
    "shellingham==1.5.4",
    "simplejson==3.19.3",
    "six==1.17.0",
    "sniffio==1.3.1",
    "starlette==0.40.0",
    "twilio==9.4.5",
    "typer==0.12.3",
    "typing-extensions==4.12.2",
    "ujson==5.10.0",
    "urllib3==2.2.2",
    "uvicorn==0.30.1",
    "uvloop==0.21.0",
    "watchfiles==1.0.4",
    "websockets==12.0",
    "yarl==1.18.3",
    "python-terminusgps==36.1.1",
]

[tool.ruff]
exclude = [
    ".git",
    ".gitignore",
    ".venv",
    "venv",
    ".vscode",
    "__pycache__",
    "node_modules",
    "site-packages",
    "dist",
    "build",
]
line-length = 88
indent-width = 4
target-version = "py311"

[tool.ruff.lint]
select = [
    "E4",
    "E7",
    "E9",
    "F",
]
ignore = ["F821"]
fixable = [ "ALL" ]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = false
skip-magic-trailing-comma = true
